version: '3'
services:
  play-sandbox:
    container_name: play-sandbox
    image: "golang/playground-sandbox"
    networks:
      - default
      - app_net
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  play:
    container_name: play
    build: ./playground
    networks:
      - default
      - app_net
    volumes:
      - /data/playground/snippet:/app/snippet:rw
    depends_on:
      - play-sandbox
    links:
      - play-sandbox:play-sandbox
    environment:
      - SANDBOX_BACKEND_URL=http://play-sandbox/run
    restart: always
    command: /app/playground
  
  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - play
    links:
      - play:play
    volumes:
      - /data/www:/data/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs/:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx:rw
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'
  
  mysql:
    container_name: mysql
    image: "mysql:8.0"
    networks:
      - default
      - app_net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=lmm7xyx
    volumes:
      - ../../mysql:/var/lib/mysql
    restart: always

networks:
  app_net:
    external: true
